title: Korobi's logs
description: >
    This is the korobi's blog where you'll find updates about
    the site and the bots as well as insights of our development
    adventures

url: "https://blog.korobi.io"
baseurl: ""
permalink: "/:year/:month/:day/:title/"
timezone: UTC

exclude:
    - README.md

gems:
    - jemoji
    - jekyll-feed
    - jekyll-mentions

markdown: redcarpet
redcarpet:
    extensions:
        - no_intra_emphasis
        - autolink
        - strikethrough
        - fenced_code_blocks

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
