title: Korobi's logs
description: > # this means to ignore newlines until "baseurl:"
    This is the korobi's blog where you'll find updates about
    the site and the bots as well as insights of our development
    adventures

url: "https://blog.korobi.io/"
baseurl: ""
permalink: "/:year/:month/:day/:title/"

# Build settings
markdown: kramdown

